create database Project_3;

-- ==========================================
-- basic queries
-- ==========================================

-- display all records from the sales table
select * from sales;

-- display the first 10 records
select * from sales
limit 10;

-- count the total number of orders
select count(*) as total_orders
from sales;

-- display the table structure
describe sales;

-- display all unique payment methods
select distinct paymentmethod
from sales;

-- display all unique order statuses
select distinct orderstatus
from sales;

-- display all unique referral sources
select distinct referralsource
from sales;

-- count the total number of unique customers
select count(distinct customerid) as unique_customers
from sales;

-- count the total number of unique products
select count(distinct product) as unique_products
from sales;

-- display order id, product and total price
select orderid, product, totalprice
from sales;

-- ==========================================
-- filtering queries
-- ==========================================

-- display orders where quantity is greater than 3
select * from sales
where quantity > 3;

-- display orders paid using credit card
select * from sales
where paymentmethod = 'Credit Card';

-- display completed orders
select * from sales
where orderstatus = 'Delivered';

-- display orders where total price is greater than 1000
select * from sales
where totalprice > 1000;

-- display orders where total price is between 500 and 2000
select * from sales
where totalprice between 500 and 2000;

-- display orders where payment method is cash
select * from sales
where paymentmethod in ('Cash');

-- display products whose name contains the letter 'a'
select * from sales
where product like '%a%';

-- display orders where quantity is greater than 2 and total price is greater than 1000
select * from sales
where quantity > 2 and totalprice > 1000;

-- display orders sorted by total price in descending order
select * from sales
order by totalprice desc;

-- display the top 5 highest value orders
select * from sales
order by totalprice desc
limit 5;

-- display orders that are either delivered or paid by cash
select *
from sales
where orderstatus = 'Delivered'
or paymentmethod = 'Cash';

-- ==========================================
-- aggregate functions
-- ==========================================

-- calculate the total revenue generated
select sum(TotalPrice) as total_revenue
from sales;

-- calculate the average order value
select round(avg(totalprice), 2) as average_order_value
from sales;

-- display the highest and lowest order value
select max(totalprice) as highest_order_value,
       min(totalprice) as lowest_order_value
from sales;

-- display the highest and lowest quantity ordered
select max(quantity) as highest_quantity,
       min(quantity) as lowest_quantity
from sales;

-- ==========================================
-- group by queries
-- ==========================================

-- display the total revenue by payment method
select paymentmethod, sum(totalprice) as total_revenue
from sales
group by paymentmethod;

-- display the average order value by order status
select orderstatus, round(avg(totalprice), 2) as average_order_value
from sales
group by orderstatus;

-- display the total quantity sold for each product
select product, sum(quantity) as total_quantity_sold
from sales
group by product
order by total_quantity_sold desc;

-- display products with total revenue greater than 150000
select product, sum(totalprice) as total_revenue
from sales
group by product
having total_revenue > 150000;

-- display the number of orders placed using each payment method
select paymentmethod, count(*) as total_orders
from sales
group by paymentmethod
order by total_orders desc;

-- ==========================================
-- business insights
-- ==========================================

-- display the top 5 customers based on total spending
select customerid, sum(totalprice) as total_spent
from sales
group by customerid
order by total_spent desc
limit 5;

-- display the top 5 best selling products based on quantity sold
select product, sum(quantity) as total_quantity_sold
from sales
group by product
order by total_quantity_sold desc
limit 5;

-- display the total revenue generated by each payment method
select paymentmethod, sum(totalprice) as total_revenue
from sales
group by paymentmethod
order by total_revenue desc;

-- display the average order value for each payment method
select paymentmethod, round(avg(totalprice), 2) as average_order_value
from sales
group by paymentmethod
order by average_order_value desc;

-- display the number of orders received from each referral source
select referralsource, count(*) as total_orders
from sales
group by referralsource
order by total_orders desc;

-- display the products with revenue greater than 100000
select product, sum(totalprice) as total_revenue
from sales
group by product
having total_revenue > 100000
order by total_revenue desc;

-- display the monthly sales revenue
select month(str_to_date(date,'%d-%m-%Y')) as month_number, sum(totalprice) as total_sales
from sales
group by month(str_to_date(date,'%d-%m-%Y'))
order by month_number;